cropper:
  cropR: 1.0
  cropZ: 1.0
  mesh: 0.001
picker:
  zDiff: 0.3
  zRot: 3.14
rovi:
  live:
    camera:
      ExposureTime: 300000
      Gain: 50
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 255
      Mode: ''
searcher:
  distance_threshold: 1.5
  icp_threshold: 5.0
  feature_max_nn: 100
  feature_radius: 5.0
  normal_max_nn: 30
  normal_radius: 2.0
