cropper:
  cropR: 0.08
  cropZ: 0.42
  mesh: 0.001
  ladC: 100000
  ladW: 0
picker:
  azimuth:
    min: 0
    max: 1
  fitness:
    min: 0.8
    max: 1
rovi:
  live:
    camera:
      ExposureTime: 300000
      Gain: 50
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 255
      Mode: ''
searcher:
  distance_threshold: 1.5
  icp_threshold: 5.0
  feature_max_nn: 100
  feature_radius: 5.0
  normal_max_nn: 30
  normal_radius: 2.0
