config:
  searcher:
    scenes: ["surface"]
    scene_frame_id: ["camera/capture0"]
    master_frame_id: ["camera/master0"]
    solve_frame_id: "camera/capture0"
    org_frame_id: "camera/master0"
    tf_delay: 0.1
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/rovi/X1"
  picker:
    frame_id: "pick"

