config:
  frame:
    frame_id: "camera/capture0"
  searcher:
    lines: ["surface"]
    scene_frame_id: ["camera/capture0"]
    master_frame_id: ["camera/master0"]
    place_frame_id: "camera/capture0"
    tf_delay: 0.1
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/rovi/X1"
  picker:
    start_frame_id: "master/camera0"
    goal_frame_id: "solve"
