config:
  frame:
    frame_id: "camera/capture0"
  searcher:
    lines: ["surface"]
    scene_frame_id: ["camera/capture0"]
    master_frame_id: ["camera/master0"]
    place_frame_id: "camera/capture0"
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/filer/load"
