cropper:
  cropR: 3000
  cropZ: 800
  ladC: 0
  ladW: 0
  mesh: 1
picker:
  azimuth:
    max: 2
    min: 0
  fitness:
    max: 1
    min: 0.7
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
      Gain: 100
  pshift_genpc:
    camera:
      ExposureTime: 16800
      Gain: 0
    projector:
      Intencity: 200
      Mode: 1
searcher:
  distance_threshold: 3
  feature_max_nn: 100
  feature_radius: 25
  icp_threshold: 2
  normal_max_nn: 30
  normal_radius: 10
