cropper:
  cropR: 200
  cropZ: 600
  ladC: 0
  ladW: 0
  mesh: 3
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.35
rovi:
  live:
    camera:
      ExposureTime: 20000
      Gain: 50
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 120
      Mode: 1
searcher:
  distance_threshold: 20
  feature_max_nn: 100
  feature_radius: 10
  icp_threshold: 3
  normal_max_nn: 30
  normal_radius: 6
