cropper:
  cropR: 3000
  cropZ: 800
  ladC: 0
  ladW: 0
  mesh: 1
  nfmin: 0
  nfrad: 0
picker:
  azimuth:
    max: 2
    min: 0
  fitness:
    max: 1
    min: 0.7
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
      Gain: 100
  pshift_genpc:
    camera:
      ExposureTime: 16800
      Gain: 0
    projector:
      Intencity: 200
      Mode: 1
searcher:
  distance_threshold: 3
  feature_mesh: 2
  feature_radius: 25
  icp_threshold: 1
  normal_min_nn: 0
  normal_radius: 10
  repeat: 3
  rotate: 0
