cropper:
  cropR: 0.08
  cropZ: 0.42
  mesh: 0.001
  ladle: 100000
picker:
  transform:
    zDiff: 0.3
    zRot: 3.14
  fitness:
    min: 0.8
    max: 1
rovi:
  live:
    camera:
      ExposureTime: 300000
      Gain: 63
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 150
      Mode: 1
searcher:
  distance_threshold: 0.01
  feature_max_nn: 100
  feature_radius: 0.03
  icp_threshold: 0.005
  normal_max_nn: 30
  normal_radius: 0.01
